/* Deterministic, frame-rate independent game rules. No market data. */
class PenguEngine {
 constructor(random=Math.random){this.random=random;this.reset()}
 reset(){this.time=0;this.lane=1;this.health=3;this.energy=0;this.price=.009;this.peak=.009;this.coins=0;this.combo=0;this.shield=false;this.entities=[];this.nextRow=.8;this.done=false;this.invulnerable=0;this.notices=[];this.effects=[]}
 move(dir){if(!this.done)this.lane=Math.max(0,Math.min(2,this.lane+dir))}
 get phase(){return this.time<10?0:this.time<20?1:this.time<27?2:3}
 updatePrice(){this.energy=Math.max(0,Math.min(125,this.energy));this.price=.009*Math.pow(1/.009,this.energy/100);this.peak=Math.max(this.peak,this.price)}
 row(){const r=this.random;const blocked=Math.floor(r()*3);const rewardLane=(blocked+1+Math.floor(r()*2))%3;const phase=this.phase;const hazard=phase===0?'cart':phase===1?'red':r()<.5?'bear':'rug';this.entities.push({lane:blocked,age:0,type:hazard,reward:false});let type=r()<.12?'diamond':phase===0?'toy':phase===1?'coin':r()<.5?'green':'fish';this.entities.push({lane:rewardLane,age:0,type,reward:true});if(phase===1&&r()<.6)this.entities.push({lane:(3-blocked-rewardLane),age:0,type:'coin',reward:true})}
 step(dt){if(this.done)return;dt=Math.min(.05,Math.max(0,dt));this.time=Math.min(30,this.time+dt);this.invulnerable=Math.max(0,this.invulnerable-dt);this.energy+=dt*.85;if(this.time>=this.nextRow&&this.time<28){this.row();this.nextRow=this.time+(this.phase===2?.64:.76)}for(const e of this.entities){e.age+=dt;if(e.age>=2.35&&!e.hit){e.hit=true;if(e.lane===this.lane)this.hit(e)}}this.entities=this.entities.filter(e=>e.age<2.7);this.updatePrice();if(this.health<=0||this.time>=30)this.done=true}
 hit(e){if(e.reward){if(e.type==='diamond'){this.shield=true;this.notices.push('鑽石手上線 💎');this.effects.push({kind:'shield',lane:e.lane,type:e.type})}else{this.coins++;this.combo++;this.energy+=(e.type==='coin'?1.3:e.type==='green'?1.4:1.0)+Math.min(2.2,Math.max(0,this.combo-10)*.12);this.effects.push({kind:'collect',lane:e.lane,type:e.type,combo:this.combo});if(this.combo%5===0)this.notices.push(`${this.combo} COMBO！企鵝起飛 🚀`)}}else if(this.invulnerable<=0){this.combo=0;if(this.shield){this.shield=false;this.notices.push('Still holding. 💎');this.effects.push({kind:'block',lane:e.lane})}else{this.health--;this.energy-=12;this.effects.push({kind:'damage',lane:e.lane});this.notices.push(e.type==='rug'?'我本來就打算長期持有。':e.type==='cart'?'借過！企鵝送貨中！':'Healthy correction. 😅')}this.invulnerable=.8}}
}
if(typeof window!=='undefined')window.PenguEngine=PenguEngine;
if(typeof module!=='undefined')module.exports=PenguEngine;
