'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),penguin=new Image();
const engine=new PenguEngine();let mode='ready',last=0,visualTime=0,phaseShown=-1,eventUntil=0,bubbleUntil=0,soundOn=false,audio=null,displayLane=1,lastMove=0,checkpoint=new Set(),best=.009;
try{best=Math.max(.009,Number(localStorage.getItem('pengu-best-v1'))||.009)}catch{}
const money=n=>'$'+(n>=1?n.toFixed(2):n.toFixed(3));$('best').textContent=money(best);
const stages=[{year:'2023 → 2024 · REAL STORY',title:'玩具出征！',line:'說我只是 JPEG？我上架了啦！',color:'#59c9fa',sky:'#c3f3ff'}, {year:'DEC 2024 · REAL STORY',title:'PENGU 空投派對',line:'魚先不用，我接一下空投！',color:'#65cceb',sky:'#ccffed'}, {year:'MEME MODE · GAME EVENT',title:'熊市追逐！',line:'BTC −10%？ I’m fine. 😅',color:'#4d67b4',sky:'#bca8ef'}, {year:'NEXT CHAPTER · DREAM MODE',title:'最後衝刺 · ROAD TO $1',line:'目標很遠，企鵝繼續跑。',color:'#328bde',sky:'#8ee6ff'}];
const symbols={cart:'🛒',toy:'🧸',coin:'🪙',diamond:'💎',red:'📉',bear:'🐻',rug:'🕳️',green:'📈',fish:'🐟'};
const benchmarks={supply:62.86e9,pepe:1801937575,doge:14787233434,checked:'2026-10-01'};
function beep(kind){if(!soundOn)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.value=kind==='hit'?140:kind==='end'?660:880;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13)}catch{}}
function showEvent(year,title,line,duration=2.2){$('event-year').textContent=year;$('event-title').textContent=title;$('event-line').textContent=line;$('event').classList.add('show');eventUntil=engine.time+duration}
function say(s){$('bubble').textContent=s;$('bubble').hidden=false;bubbleUntil=engine.time+1.6}
function start(){engine.reset();mode='running';phaseShown=-1;checkpoint.clear();displayLane=1;last=performance.now();for(const id of ['start','result','paused'])$(id).hidden=true;$('pause').hidden=false;$('bubble').hidden=true;$('event').classList.remove('show');beep('start');hud()}
function move(dir){if(mode!=='running'||performance.now()-lastMove<100)return;lastMove=performance.now();engine.move(dir)}
function pause(){if(mode!=='running')return;mode='paused';$('paused').hidden=false;$('event').classList.remove('show')}
function resume(){if(mode!=='paused')return;mode='running';$('paused').hidden=true;last=performance.now()}
function rank(){return engine.price>=1?'$1 DREAM 達成 🏁':engine.health===0?'企鵝還會回來 🐧':engine.price>=.3?'Diamond Hands 💎':engine.price>=.1?'熊市倖存者 🐻':'企鵝練習生 🐟'}
function finish(){mode='result';$('result').hidden=false;$('pause').hidden=true;$('bubble').hidden=true;$('event').classList.remove('show');$('rank').textContent=rank();$('result-title').textContent=engine.price>=1?'夢想突破！你做到了。':'這次，跑到了…';$('final-price').textContent=money(engine.price);$('peak').textContent=money(engine.peak);$('coins').textContent=engine.coins+' 個';$('survived').textContent=engine.time.toFixed(1)+' 秒';let cap=engine.price*benchmarks.supply;let comparison=cap>=benchmarks.doge?'模擬市值超越 DOGE 基準 🐕':cap>=benchmarks.pepe?'模擬市值超越 PEPE 基準 🐸':'下一站：挑戰 PEPE 市值基準 🐸';$('result-line').textContent=(engine.health===0?'「我本來就打算長期持有。」':'離 $1 還有一段路，再挑戰一次？')+' '+comparison;if(engine.peak>best){best=engine.peak;$('best').textContent=money(best);try{localStorage.setItem('pengu-best-v1',best)}catch{}}beep('end')}
function hud(){$('price').textContent=money(engine.price);$('clock').innerHTML=Math.max(0,30-engine.time).toFixed(1)+'<small>秒</small>';$('hearts').textContent='♥ '.repeat(engine.health)+'♡ '.repeat(3-engine.health);$('combo').textContent=engine.shield?'DIAMOND SHIELD 💎':engine.combo>1?engine.combo+' COMBO 🔥':'ROAD TO $1';$('progress').style.width=Math.min(100,engine.energy)+'%'}
function rounded(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function poly(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function draw(){let W=1000,H=canvas.height,phase=engine.phase,s=stages[phase],horizon=H*.35,ground=H*.86;let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,s.color);sky.addColorStop(.6,s.sky);sky.addColorStop(1,'#d8f8ff');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
// Abstract ice planes and lane geometry. Gameplay symbols are rendered as emoji.
poly([[0,H*.50],[360,horizon],[440,horizon],[0,H]],phase===2?'#9bb4dc':'#b3e9f8');poly([[W,H*.47],[620,horizon],[565,horizon],[W,H]],phase===2?'#7c95c9':'#86d8f1');
poly([[365,horizon],[635,horizon],[970,H],[30,H]],phase===2?'#abcfe6':'#e7fbff');poly([[365,horizon],[385,horizon],[68,H],[30,H]],'#ffffffb0');poly([[615,horizon],[635,horizon],[970,H],[932,H]],'#ffffffb0');
for(let lane=0;lane<2;lane++){let top=455+lane*90,bottom=343+lane*314;ctx.strokeStyle=phase===2?'#8099c5':'#82d3eb';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(top,horizon);ctx.lineTo(bottom,H);ctx.stroke()}
for(let i=0;i<10;i++){let t=((i/10+visualTime*.24)%1),y=horizon+(H-horizon)*t*t,half=135+335*t*t;ctx.strokeStyle='#81bdd52b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(500-half,y);ctx.lineTo(500+half,y);ctx.stroke()}
ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 18px system-ui';
if(phase===0){for(let side of [-1,1]){let x=500+side*355;rounded(x-90,H*.43,180,65,10,'#ffffffd9');ctx.fillStyle='#1480bc';ctx.fillText('PUDGY TOYS',x,H*.43+32);ctx.font='48px system-ui';ctx.fillText('🧸 🐧',x,H*.59);ctx.font='900 18px system-ui'}}
if(phase===1){ctx.font='55px system-ui';for(let i=0;i<4;i++){let x=130+i*250,y=horizon-30+Math.sin(visualTime+i)*16;ctx.fillText('🪂',x,y)}}
if(phase===2){ctx.font='78px system-ui';ctx.fillText('🐻',120,H*.72);ctx.fillText('🐻',885,H*.64);ctx.font='900 20px system-ui';ctx.fillStyle='#fff';ctx.fillText('FUD FM 📣',110,H*.64)}
if(phase===3){rounded(385,horizon-76,230,56,14,'#ffffffdf');ctx.fillStyle='#0877d1';ctx.font='900 25px system-ui';ctx.fillText('$1 DREAM 🏁',500,horizon-48)}
let ents=engine.entities.slice().sort((a,b)=>a.age-b.age);for(let e of ents){let t=Math.min(1.12,e.age/2.35),depth=t*t,y=horizon+(ground-horizon)*depth,x=500+(e.lane-1)*(90+180*depth),size=28+76*depth;if(e.hit)continue;ctx.save();if(e.reward){ctx.shadowColor=e.type==='diamond'?'#59dcff':'#ffd352';ctx.shadowBlur=10+depth*15;ctx.fillStyle='#fff6';ctx.beginPath();ctx.ellipse(x,y+size*.4,size*.43,size*.14,0,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#ce466b35';ctx.beginPath();ctx.ellipse(x,y+size*.3,size*.45,size*.17,0,0,Math.PI*2);ctx.fill()}ctx.font=size+'px system-ui';ctx.fillText(symbols[e.type],x,y);ctx.restore()}
let px=500+(displayLane-1)*270,py=ground-15,sz=195,bob=Math.sin(visualTime*13)*(mode==='running'?6:3);ctx.fillStyle='#27779938';ctx.beginPath();ctx.ellipse(px,py+70,65,15,0,0,Math.PI*2);ctx.fill();if(engine.shield){ctx.strokeStyle='#8ef5ff';ctx.lineWidth=5;ctx.shadowColor='#69eaff';ctx.shadowBlur=24;ctx.beginPath();ctx.ellipse(px,py-15,105,115,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}if(engine.invulnerable>0&&Math.floor(visualTime*12)%2===0)ctx.globalAlpha=.45;if(penguin.complete&&penguin.naturalWidth)ctx.drawImage(penguin,px-sz/2,py-sz*.72+bob,sz,sz);ctx.globalAlpha=1;
// Snow particles are non-representational ambience, never obscure obstacles.
ctx.fillStyle='#ffffff9c';for(let i=0;i<35;i++){let x=(i*127+Math.sin(i)*50+visualTime*18)%W,y=(i*89+visualTime*55)%(H*.75);ctx.beginPath();ctx.arc(x,y,i%3+1,0,Math.PI*2);ctx.fill()}
}
function resize(){let r=canvas.getBoundingClientRect();canvas.width=1000;canvas.height=Math.round(1000*r.height/r.width);draw()}
function frame(now){let dt=Math.min(.05,(now-last)/1000||0);last=now;visualTime+=dt;displayLane+=(engine.lane-displayLane)*Math.min(1,dt*18);if(mode==='running'){let hp=engine.health,coins=engine.coins;engine.step(dt);if(hp>engine.health)beep('hit');else if(coins<engine.coins)beep('coin');if(phaseShown!==engine.phase){phaseShown=engine.phase;let s=stages[phaseShown];showEvent(s.year,s.title,s.line)}let cap=engine.price*benchmarks.supply;for(let [name,value,emoji] of [['PEPE',benchmarks.pepe,'🐸'],['DOGE',benchmarks.doge,'🐕'],['$1',benchmarks.supply,'🏁']]){if(cap>=value&&!checkpoint.has(name)){checkpoint.add(name);say(name==='$1'?'$1 DREAM！傳說企鵝 🏁':`模擬市值超越 ${name}！${emoji}`)}}if(engine.notices.length)say(engine.notices.splice(0).pop());if(engine.time>eventUntil)$('event').classList.remove('show');if(engine.time>bubbleUntil)$('bubble').hidden=true;hud();if(engine.done)finish()}draw();requestAnimationFrame(frame)}
$('play').onclick=start;$('retry').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);
$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='音效 '+(soundOn?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');beep('coin')};
window.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;if(['ArrowLeft','ArrowRight','a','d','A','D','Escape',' '].includes(e.key)&&mode==='running')e.preventDefault();if(['ArrowLeft','a','A'].includes(e.key))move(-1);if(['ArrowRight','d','D'].includes(e.key))move(1);if(e.key==='Escape'){mode==='running'?pause():resume()}});
let touchX=0;canvas.addEventListener('pointerdown',e=>{touchX=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{let dx=e.clientX-touchX;if(Math.abs(dx)>18)move(dx>0?1:-1)});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('resize',resize);
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2200)}
$('share').onclick=()=>{let text=`🐧 我把 PENGU 跑到了 ${money(engine.price)}！\n${rank()}｜30 秒 Road to $1\n你能跑多遠？\n（價格為遊戲成績）`;window.open('https://twitter.com/intent/tweet?text='+encodeURIComponent(text)+'&url='+encodeURIComponent(location.href),'_blank','noopener')};
$('download').onclick=()=>{try{let c=document.createElement('canvas');c.width=1080;c.height=1080;let g=c.getContext('2d');let bg=g.createLinearGradient(0,0,0,1080);bg.addColorStop(0,'#0977df');bg.addColorStop(1,'#8ce7ff');g.fillStyle=bg;g.fillRect(0,0,1080,1080);g.fillStyle='#fff';g.textAlign='center';g.font='900 48px sans-serif';g.fillText('PENGU RUN · ROAD TO $1',540,110);g.font='900 32px sans-serif';g.fillText(rank(),540,188);g.drawImage(penguin,340,220,400,400);g.font='900 100px sans-serif';g.fillText(money(engine.price),540,740);g.font='28px sans-serif';g.fillText('本場最高 '+money(engine.peak)+'  ·  收集 '+engine.coins+' 個',540,810);g.fillText('你能帶 PENGU 跑多遠？',540,880);g.font='22px sans-serif';g.fillText('OPEN PENGU · 企鵝開講',540,978);g.font='18px sans-serif';g.fillText('遊戲成績｜$0.009 假設起跑｜$1 夢想終點',540,1020);c.toBlob(blob=>{if(!blob)return toast('圖片未能產生，請再試一次');let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pengu-run-result.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)},'image/png')}catch{toast('無法下載戰績卡，請再試一次')}};
penguin.onload=()=>{$('play').disabled=false;$('play').textContent='開始挑戰';draw()};penguin.onerror=()=>{$('play').textContent='圖片未載入，點此重試';$('play').disabled=false;$('play').onclick=()=>{penguin.src='pengu.png?retry='+Date.now()}};penguin.src='pengu.png';resize();requestAnimationFrame(frame);
// Optional agent interface uses the same visible state and actions.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_game_state',description:'Read the current Pengu Run game state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,time:engine.time,price:engine.price,health:engine.health,lane:engine.lane})},{name:'start_game',description:'Start or restart a 30-second Pengu Run game, resetting current progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(input&&Object.keys(input).length)throw Error('No arguments accepted');if(!penguin.naturalWidth)throw Error('Character still loading');start();return{mode,price:engine.price}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
