'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),penguin=new Image(),snowWorld=new Image(),atlas=new Image(),runner=new Image();
const engine=new PenguEngine();let mode='ready',last=0,visualTime=0,phaseShown=-1,eventUntil=0,bubbleUntil=0,soundOn=false,audio=null,displayLane=1,checkpoint=new Set(),best=.01,particles=[],rings=[],floaters=[],hitFlash=0,phaseFlash=0,lastCombo=0,reactionUntil=0,reactionFrame=0,priceDeltaUntil=0;
const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
const lowPower=window.innerWidth<700;
const atlasCells={cart:[0,0],toy:[1,0],coin:[2,0],diamond:[0,1],red:[1,1],bear:[2,1],rug:[0,2],green:[1,2],fish:[2,2]};
try{best=Math.max(.01,Number(localStorage.getItem('pengu-best-v1'))||.01)}catch{}
const money=n=>'$'+(n>=1?n.toFixed(2):n.toFixed(n<.1?5:4));$('best').textContent=money(best);
const stages=[{year:'2023 → 2024 · REAL STORY',title:'玩具出征！',line:'說我只是 JPEG？我上架了啦！',color:'#59c9fa',sky:'#c3f3ff'}, {year:'DEC 2024 · REAL STORY',title:'PENGU 空投派對',line:'魚先不用，我接一下空投！',color:'#65cceb',sky:'#ccffed'}, {year:'MEME MODE · GAME EVENT',title:'熊市追逐！',line:'BTC −10%？ I’m fine. 😅',color:'#4d67b4',sky:'#bca8ef'}, {year:'BULL COMEBACK · GAME EVENT',title:'牛市反攻！',line:'別急著慶祝，前面還有洞！',color:'#328bde',sky:'#8ee6ff'}];
const symbols={cart:'🛒',toy:'🧸',coin:'🪙',diamond:'💎',red:'📉',bear:'🐻',rug:'🕳️',green:'📈',fish:'🐟'};
const benchmarks={supply:62.86e9,pepe:1801937575,doge:14787233434,checked:'2026-10-01'};
const languages=['zh-Hant','en','ko','ja'];let language='en',langIndex=1,lastBubble='',characterReady=false,characterFailed=false;
try{const saved=localStorage.getItem('pengu-language-v1');if(languages.includes(saved))language=saved}catch{}
langIndex=languages.indexOf(language);
function t(key,values={}){return PenguI18n.keys[key][langIndex].replace(/\{(\w+)\}/g,(_,k)=>values[k]??'{'+k+'}')}
function translateNotice(s){if(typeof s==='object')return t(s.key,s.values)+(s.suffix||'');const notice=PenguI18n.notices.find(row=>row[0]===s);if(notice)return notice[langIndex];const combo=s.match(/^(\d+) COMBO/);return combo?t('comboNotice',{n:combo[1]}):s}
function soundLabel(){$('sound').textContent=t('sound')+' '+t(soundOn?'enabled':'disabled');$('sound').setAttribute('aria-label',t(soundOn?'soundOff':'soundOn'))}
function applyLanguage(value){if(!languages.includes(value))return;language=value;langIndex=languages.indexOf(value);document.documentElement.lang=value;$('language').value=value;for(const [selector,...translations] of PenguI18n.rows)document.querySelector(selector).innerHTML=translations[langIndex];$('arena').setAttribute('aria-label',t('arena'));canvas.setAttribute('aria-label',t('canvas'));$('nft-preview').alt=t('preview');$('animated-preview').setAttribute('aria-label',t('animation'));$('settings-toggle').setAttribute('aria-label',t('settings'));$('settings-toggle').setAttribute('title',t('settings'));$('exit-play').textContent='↩';$('exit-play').setAttribute('aria-label',t('exit'));$('exit-play').setAttribute('title',t('exit'));soundLabel();$('play').textContent=t(characterFailed?'loadError':characterReady?'play':'loading');for(let i=0;i<stages.length;i++){stages[i].year=t('year'+i);stages[i].title=PenguI18n.stages[i][0][langIndex];stages[i].line=PenguI18n.stages[i][1][langIndex]}document.querySelector('h1 span').textContent=t('road');if(phaseShown>=0){$('event-year').textContent=stages[phaseShown].year;$('event-title').textContent=stages[phaseShown].title;$('event-line').textContent=stages[phaseShown].line}if(lastBubble)$('bubble').textContent=translateNotice(lastBubble);hud();if(mode==='result')renderResult();try{localStorage.setItem('pengu-language-v1',value)}catch{}resize()}
function beep(kind){if(!soundOn)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const at=audio.currentTime;const tone=(freq,end,delay,length,type,volume)=>{let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=type;o.frequency.setValueAtTime(freq,at+delay);o.frequency.exponentialRampToValueAtTime(end,at+delay+length);g.gain.setValueAtTime(.001,at+delay);g.gain.linearRampToValueAtTime(volume,at+delay+.01);g.gain.exponentialRampToValueAtTime(.001,at+delay+length);o.start(at+delay);o.stop(at+delay+length+.02)};if(kind==='hit'||kind==='penalty'){tone(180,45,0,.28,'sawtooth',.075);tone(65,30,.025,.35,'triangle',.1)}else if(kind==='shield'||kind==='block'){tone(650,1300,0,.18,'sine',.055);tone(1000,1600,.07,.24,'sine',.045)}else if(kind==='end'){[660,440,220].forEach((f,i)=>tone(f,f*.8,i*.12,.2,'triangle',.07))}else{[880,1320,1760].forEach((f,i)=>tone(f,f*1.04,i*.055,.12,'sine',.045))}}catch{}}
function showEvent(year,title,line,duration=2.2){$('event-year').textContent=year;$('event-title').textContent=title;$('event-line').textContent=line;$('event').hidden=false;$('event').classList.add('show');phaseFlash=reducedMotion?0:.55;eventUntil=engine.time+duration}
function say(s){lastBubble=s;$('bubble').textContent=translateNotice(s);$('bubble').hidden=false;bubbleUntil=engine.time+1.6}
function requestPlayFullscreen(){
 if(document.fullscreenElement||!document.documentElement.requestFullscreen)return;
 try{Promise.resolve(document.documentElement.requestFullscreen()).then(()=>{resize();last=performance.now()},()=>resize())}catch{resize()}
}
function enterPlay(){document.body.classList.add('playing');$('session-controls').append(document.querySelector('.top-actions'));$('exit-play').hidden=false;resize()}
function exitPlay(){pause();document.body.classList.remove('playing');$('header-actions').append(document.querySelector('.top-actions'));$('exit-play').hidden=true;if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});resize()}
function start(){enterPlay();requestPlayFullscreen();$('play-settings').open=false;engine.reset();mode='running';phaseShown=-1;checkpoint.clear();particles=[];rings=[];floaters=[];hitFlash=0;lastCombo=0;reactionUntil=0;reactionFrame=0;$('arena').classList.remove('combo-active','impact');displayLane=1;last=performance.now();for(const id of ['start','result','paused'])$(id).hidden=true;$('pause').hidden=false;$('bubble').hidden=true;$('event').classList.remove('show');$('event').hidden=false;$('combo-burst').hidden=true;$('price-delta').hidden=true;beep('start');hud()}
function move(dir){if(mode==='running')engine.move(dir)}
function pause(){if(mode!=='running')return;mode='paused';$('paused').hidden=false;$('event').classList.remove('show')}
function resume(){if(mode!=='paused')return;enterPlay();requestPlayFullscreen();$('play-settings').open=false;mode='running';$('paused').hidden=true;last=performance.now()}
function rank(){return engine.peak>=.3?t('diamondRank'):engine.time>=60?t('survivor'):t('rookie')}
function renderResult(){$('rank').textContent=rank();$('result-title').textContent=t('resultTitle');$('final-price').textContent=money(engine.price);$('peak').textContent=money(engine.peak);$('coins').textContent=engine.coins+t('count');$('survived').textContent=engine.time.toFixed(1)+' '+t('seconds');let cap=engine.price*benchmarks.supply;let comparison=cap>=benchmarks.doge?t('over',{name:'DOGE'})+' 🐕':cap>=benchmarks.pepe?t('over',{name:'PEPE'})+' 🐸':t('next');$('result-line').textContent=t(engine.health===0?'holding':'again')+' '+comparison;}
function finish(){mode='result';$('event').hidden=true;$('combo-burst').hidden=true;$('result').hidden=false;$('pause').hidden=true;$('bubble').hidden=true;$('event').classList.remove('show');renderResult();if(engine.peak>best){best=engine.peak;$('best').textContent=money(best);try{localStorage.setItem('pengu-best-v1',best)}catch{}}beep('end')}
function hud(){$('level').textContent=t('level',{n:engine.level});$('speed').textContent=engine.speed.toFixed(2)+'×';$('price').textContent=money(engine.price);$('clock').innerHTML=engine.time.toFixed(1)+'<small>'+t('seconds')+'</small>';$('hearts').setAttribute('aria-label',t('hearts',{n:engine.health}));$('hearts').textContent='♥ '.repeat(engine.health)+'♡ '.repeat(3-engine.health);$('combo').textContent=engine.shield?t('shield'):engine.combo>1?t('combo',{n:engine.combo}):t('road')}
function rounded(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function poly(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function drawFit(g,img,x,y,w,h){if(!img.naturalWidth)return;let k=Math.min(w/img.naturalWidth,h/img.naturalHeight),iw=img.naturalWidth*k,ih=img.naturalHeight*k;g.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
// Four run poses plus celebration and impact; visual-only, no rule changes.
function characterFrame(){if(mode==='result')return engine.health===0?5:4;if(reactionUntil>visualTime)return reactionFrame;return (mode==='running'||mode==='paused')&&!reducedMotion?Math.floor(visualTime*9)%4:0}
function drawRunner(x,y,size){if(!runner.naturalWidth)return drawFit(ctx,penguin,x-size/2,y-size*.72,size,size);const f=characterFrame(),cw=runner.naturalWidth/3,ch=runner.naturalHeight*.484375;const rowY=f<3?0:runner.naturalHeight*.48828125;const box=size*1.2;ctx.save();ctx.translate(x,y-size*.14);if(!reducedMotion){ctx.rotate((engine.lane-displayLane)*.12);const breathe=mode==='running'?1+Math.sin(visualTime*18)*.015:1;ctx.scale(1/breathe,breathe)}ctx.drawImage(runner,(f%3)*cw,rowY,cw,ch,-box/2,-box*.66,box,box);ctx.restore()}
function icon(type,x,y,size){if(atlas.naturalWidth){const cell=atlasCells[type],cw=atlas.naturalWidth/3,ch=atlas.naturalHeight/3;ctx.drawImage(atlas,cell[0]*cw,cell[1]*ch,cw,ch,x-size/2,y-size/2,size,size)}else{ctx.font=size+'px system-ui';ctx.fillText(symbols[type],x,y)}}
function sparkle(x,y,size,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x+size*.25,y-size*.25);ctx.lineTo(x+size,y);ctx.lineTo(x+size*.25,y+size*.25);ctx.lineTo(x,y+size);ctx.lineTo(x-size*.25,y+size*.25);ctx.lineTo(x-size,y);ctx.lineTo(x-size*.25,y-size*.25);ctx.closePath();ctx.fill()}
function burst(lane,kind,combo=0,delta=0){reactionFrame=kind==='damage'||kind==='penalty'||kind==='block'?5:4;reactionUntil=visualTime+(kind==='collect'?.22:.65);let x=500+(lane-1)*270,y=canvas.height*(canvas.height<600?.79:.86)-35;let color=kind==='damage'||kind==='penalty'?'#ff5274':kind==='shield'||kind==='block'?'#73f5ff':'#ffdf70';let count=reducedMotion?4:lowPower?22:42;for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,s=80+Math.random()*230;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-70,life:.65+Math.random()*.35,total:1,color,size:3+Math.random()*6})}rings.push({x,y,life:.5,color});if(kind==='collect')floaters.push({x,y:y-65,life:.8,text:'+'+money(Math.max(0,delta)),color:'#38e7a3'});if(kind==='damage'||kind==='penalty'){hitFlash=reducedMotion?.12:.5;floaters.push({x,y:y-85,life:1,text:kind==='penalty'?(delta<0?'−'+money(-delta):t('priceFloor')):t('lossHP'),color:'#ff5274'});if(!reducedMotion){$('arena').classList.remove('impact');void $('arena').offsetWidth;$('arena').classList.add('impact')}}if(kind==='collect'||kind==='penalty'){$('price-delta').textContent=(delta>0?'+':delta<0?'−':'')+(delta===0?t('priceFloor'):money(Math.abs(delta)));$('price-delta').dataset.direction=delta>0?'up':'down';$('price-delta').hidden=false;priceDeltaUntil=engine.time+1}beep(kind==='damage'?'hit':kind);if(kind==='collect'&&combo>=5&&combo%5===0){$('combo-burst').hidden=false;$('combo-burst').innerHTML='<strong>'+combo+'</strong><span>'+t('comboLabel')+'</span>';lastCombo=engine.time+.85;$('arena').classList.add('combo-active')}}
function updateFX(dt){particles=particles.filter(p=>p.life>0);for(let p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=160*dt}rings=rings.filter(p=>p.life>0);for(let p of rings)p.life-=dt;floaters=floaters.filter(p=>p.life>0);for(let p of floaters){p.life-=dt;p.y-=70*dt}hitFlash=Math.max(0,hitFlash-dt);phaseFlash=Math.max(0,phaseFlash-dt)}
function draw(){let W=1000,H=canvas.height,phase=engine.phase,s=stages[phase],horizon=H*.35,ground=H*(H<600?.79:.86);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,s.color);sky.addColorStop(.6,s.sky);sky.addColorStop(1,'#d8f8ff');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
if(snowWorld.naturalWidth){let iw=snowWorld.naturalWidth,ih=snowWorld.naturalHeight;let k=Math.max(W/iw,H/ih);ctx.drawImage(snowWorld,(W-iw*k)/2,(H-ih*k)/2,iw*k,ih*k)}
// Snow piste is a translucent play surface over the illustrated landscape.
if(phase===2){ctx.fillStyle='#17265355';ctx.fillRect(0,0,W,H)}else if(phase===1){ctx.fillStyle='#65ffd70c';ctx.fillRect(0,0,W,H)}
let road=ctx.createLinearGradient(0,horizon,0,H);road.addColorStop(0,'#ffffff26');road.addColorStop(1,phase===2?'#d9eeffcf':'#f6fcffe0');
poly([[365,horizon],[635,horizon],[970,H],[30,H]],road);
for(let side of [-1,1]){ctx.strokeStyle='#ffffffcf';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(500+side*135,horizon);ctx.lineTo(500+side*470,H);ctx.stroke();ctx.strokeStyle='#8bc5e766';ctx.lineWidth=3;ctx.stroke()}
for(let lane=0;lane<2;lane++){ctx.strokeStyle='#64a9d336';ctx.lineWidth=3;ctx.setLineDash([12,24]);ctx.beginPath();ctx.moveTo(455+lane*90,horizon);ctx.lineTo(343+lane*314,H);ctx.stroke();ctx.setLineDash([])}
// Sparse moving snow-track marks give speed without cluttering collectibles.
for(let i=0;i<9;i++){let t=(i/9+visualTime*.24*engine.speed)%1,y=horizon+(H-horizon)*t*t,half=135+335*t*t;ctx.strokeStyle='#9ac9e928';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(500-half,y);ctx.lineTo(500+half,y);ctx.stroke()}
ctx.textAlign='center';ctx.textBaseline='middle';
if(phase===0){for(let side of [-1,1]){let x=500+side*365;rounded(x-94,H*.42,188,55,13,'#092d5dcf');ctx.fillStyle='#fff';ctx.font='900 17px system-ui';ctx.fillText('PUDGY TOYS',x,H*.42+28);icon('toy',x,H*.55,105)}}
if(phase===1){for(let i=0;i<4;i++){let x=110+i*260,y=horizon-30+Math.sin(visualTime+i)*16;ctx.globalAlpha=.75;icon('coin',x,y,64);ctx.globalAlpha=1;ctx.strokeStyle='#fff9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y-30);ctx.quadraticCurveTo(x-30,y-80,x-40,y-40);ctx.stroke()}}
if(phase===2){icon('bear',95,H*.65,155);icon('bear',910,H*.61,120);rounded(20,H*.55,160,40,10,'#6e224ecc');ctx.font='900 18px system-ui';ctx.fillStyle='#fff';ctx.fillText(t('fud'),100,H*.55+20)}
if(phase===3){rounded(375,horizon-70,250,58,16,'#0c346bef');ctx.fillStyle='#ffdf80';ctx.font='900 27px system-ui';ctx.fillText(t('dream'),500,horizon-40)}
let ents=engine.entities.slice().sort((a,b)=>a.age-b.age);for(let e of ents){let t=Math.min(1.12,e.age/2.35),depth=t*t,y=horizon+(ground-horizon)*depth,x=500+(e.lane-1)*(90+180*depth),size=28+76*depth;if(e.hit)continue;ctx.save();if(e.reward){ctx.shadowColor=e.type==='diamond'?'#59dcff':'#ffd352';ctx.shadowBlur=10+depth*15;ctx.fillStyle='#fff6';ctx.beginPath();ctx.ellipse(x,y+size*.4,size*.43,size*.14,0,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#ce466b35';ctx.beginPath();ctx.ellipse(x,y+size*.3,size*.45,size*.17,0,0,Math.PI*2);ctx.fill()}icon(e.type,x,y,size*1.5);ctx.restore()}
let px=500+(displayLane-1)*270,py=ground-15,sz=Math.min(205,H*.28),bob=reducedMotion?0:Math.sin(visualTime*13*engine.speed)*(mode==='running'?5:1);
// The original NFT stays 2D, with its exact sleepy expression and fishing hat.
ctx.fillStyle='#173d682d';ctx.beginPath();ctx.ellipse(px,py+44,67,14,0,0,Math.PI*2);ctx.fill();
if(mode==='running'&&!reducedMotion){for(let i=0;i<8;i++){let age=((visualTime*5+i/8)%1);ctx.globalAlpha=(1-age)*.65;ctx.fillStyle=engine.combo>10?'#ffd45b':'#fff';ctx.beginPath();ctx.ellipse(px+(i%2?1:-1)*(20+age*50),py+78+age*45,4+age*8,2+age*4,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
if(engine.combo>10){let halo=ctx.createRadialGradient(px,py-15,10,px,py-15,130);halo.addColorStop(0,'#ffd77200');halo.addColorStop(.75,'#ffc85738');halo.addColorStop(1,'#ffc85700');ctx.fillStyle=halo;ctx.fillRect(px-135,py-150,270,280)}
if(engine.shield){const shieldScale=sz/205;ctx.save();ctx.translate(px,py-18);ctx.scale(shieldScale,shieldScale);ctx.translate(-px,-(py-18));ctx.strokeStyle='#48eaff';ctx.lineWidth=4;ctx.shadowColor='#12d6ff';ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(px,py-18,110,120,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#ffffffb0';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(px,py-18,103,113,0,0,Math.PI*2);ctx.stroke();if(!reducedMotion){for(let i=0;i<4;i++){let a=visualTime*2+i*Math.PI/2;sparkle(px+110*Math.cos(a),py-18+120*Math.sin(a),7,'#d0ffff')}}ctx.restore()}
ctx.save();if(engine.invulnerable>0&&!reducedMotion&&Math.floor(visualTime*12)%2===0)ctx.globalAlpha=.55;
drawRunner(px,py+bob,sz);ctx.restore();
for(let p of rings){ctx.save();ctx.globalAlpha=p.life*1.5;ctx.strokeStyle=p.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,(.5-p.life)*150+15,0,Math.PI*2);ctx.stroke();ctx.restore()}
for(let p of particles){ctx.globalAlpha=Math.max(0,p.life);sparkle(p.x,p.y,p.size,p.color)}ctx.globalAlpha=1;
for(let p of floaters){ctx.globalAlpha=Math.max(0,p.life);ctx.font='900 25px system-ui';ctx.fillStyle='#104c74';ctx.fillText(p.text,p.x,p.y)}ctx.globalAlpha=1;
ctx.fillStyle='#ffffffc0';const snowCount=reducedMotion?12:lowPower?30:60;for(let i=0;i<snowCount;i++){let x=(i*127+Math.sin(i)*50+(reducedMotion?0:visualTime*25))%W,y=(i*89+(reducedMotion?0:visualTime*65))%(H*.9);ctx.beginPath();ctx.arc(x,y,i%3+1,0,Math.PI*2);ctx.fill()}
if(mode==='running'&&phase===3&&!reducedMotion){ctx.strokeStyle='#f6ffff55';ctx.lineWidth=2;for(let i=0;i<12;i++){let side=i%2?-1:1,x=500+side*(330+i*11),y=horizon+((i*88+visualTime*450)%(H-horizon));ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+side*10,y+35);ctx.stroke()}}
if(hitFlash>0){ctx.fillStyle='rgba(255,61,105,'+Math.min(.18,hitFlash*.6)+')';ctx.fillRect(0,0,W,H)}
if(phaseFlash>0){ctx.fillStyle='rgba(210,248,255,'+phaseFlash*.15+')';ctx.fillRect(0,0,W,H)}
}

function resize(){let r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;canvas.width=1000;canvas.height=Math.round(1000*r.height/r.width);draw()}
function frame(now){let dt=Math.max(0,(now-last)/1000||0);last=now;if(dt>.5){if(mode==='running')pause();dt=0}if(mode!=='paused')visualTime+=dt;if(mode==='running'){engine.step(dt);displayLane=engine.lanePosition;for(const fx of engine.effects.splice(0))burst(fx.lane,fx.kind,fx.combo,fx.delta);updateFX(dt);if(engine.time>priceDeltaUntil)$('price-delta').hidden=true;if(engine.time>lastCombo){$('combo-burst').hidden=true;$('arena').classList.remove('combo-active')}if(phaseShown!==engine.phase){phaseShown=engine.phase;let s=stages[phaseShown];showEvent(s.year,s.title,s.line)}let cap=engine.price*benchmarks.supply;for(let [name,value,emoji] of [['PEPE',benchmarks.pepe,'🐸'],['DOGE',benchmarks.doge,'🐕']]){if(cap>=value&&!checkpoint.has(name)){checkpoint.add(name);say({key:'over',values:{name},suffix:' '+emoji})}}if(engine.notices.length)say(engine.notices.splice(0).pop());if(engine.time>eventUntil)$('event').classList.remove('show');if(engine.time>bubbleUntil)$('bubble').hidden=true;hud();if(engine.done)finish()}draw();requestAnimationFrame(frame)}
$('play-settings').ontoggle=()=>{if($('play-settings').open&&mode==='running')pause()};$('exit-play').onclick=exitPlay;$('fullscreen').onclick=async()=>{enterPlay();if(mode==='running')pause();try{if(!document.fullscreenElement){if(!document.documentElement.requestFullscreen)throw Error('unsupported');await document.documentElement.requestFullscreen()}}catch{toast(t('fullscreenUnavailable'))}resize()};
$('play').onclick=start;$('retry').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;
$('sound').onclick=()=>{soundOn=!soundOn;soundLabel();$('sound').setAttribute('aria-pressed',String(soundOn));beep('coin')};
window.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;if(['ArrowLeft','ArrowRight','a','d','A','D','Escape',' '].includes(e.key)&&mode==='running')e.preventDefault();if(['ArrowLeft','a','A'].includes(e.key))move(-1);if(['ArrowRight','d','D'].includes(e.key))move(1);if(e.key==='Escape'){mode==='running'?pause():resume()}});
// Tap and keyboard share the same simulated movement and collision position.
canvas.addEventListener('pointerdown',e=>{if(mode!=='running'||e.isPrimary===false||(e.pointerType==='mouse'&&e.button!==0))return;const r=canvas.getBoundingClientRect();if(!r.width)return;e.preventDefault();const x=Math.max(0,Math.min(.999999,(e.clientX-r.left)/r.width));engine.move(Math.floor(x*3)-engine.lane);rings.push({x:x*1000,y:(e.clientY-r.top)/r.height*canvas.height,life:.4,color:'#67dfff'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);document.addEventListener('fullscreenchange',resize);
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2200)}
$('share').onclick=()=>{let text=t('shareText',{price:money(engine.price),rank:rank()});window.open('https://twitter.com/intent/tweet?text='+encodeURIComponent(text)+'&url='+encodeURIComponent(location.href),'_blank','noopener')};
$('download').onclick=()=>{try{let c=document.createElement('canvas');c.width=1080;c.height=1080;let g=c.getContext('2d');let bg=g.createLinearGradient(0,0,0,1080);bg.addColorStop(0,'#0977df');bg.addColorStop(1,'#8ce7ff');g.fillStyle=bg;g.fillRect(0,0,1080,1080);g.fillStyle='#fff';g.textAlign='center';g.font='900 48px sans-serif';g.fillText('PENGU RUN · '+t('road'),540,110);g.font='900 32px sans-serif';g.fillText(rank(),540,188);drawFit(g,penguin,340,220,400,400);g.font='900 100px sans-serif';g.fillText(money(engine.price),540,740);g.font='28px sans-serif';g.fillText(t('cardStats',{peak:money(engine.peak),coins:engine.coins}),540,810);g.fillText(t('cardChallenge'),540,880);g.font='22px sans-serif';g.fillText(t('cardBrand'),540,978);g.font='18px sans-serif';g.fillText(t('cardNote'),540,1020);c.toBlob(blob=>{if(!blob)return toast(t('downloadError'));let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pengu-run-result.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)},'image/png')}catch{toast(t('downloadError'))}};
$('language').onchange=()=>applyLanguage($('language').value);applyLanguage(language);
penguin.onload=()=>{$('play').disabled=false;characterReady=true;characterFailed=false;$('play').onclick=start;$('play').textContent=t('play');$('nft-preview').src=penguin.src;draw()};penguin.onerror=()=>{characterFailed=true;$('play').textContent=t('loadError');$('play').disabled=false;$('play').onclick=()=>{penguin.src='nft-pengu.png?retry='+Date.now()}};runner.onload=()=>{$('nft-preview').hidden=true;$('animated-preview').hidden=false;draw()};runner.src='nft-runner.png?v=4';penguin.src='nft-pengu.png';snowWorld.src='snow-world.png';atlas.src='game-atlas.png';resize();requestAnimationFrame(frame);
// Optional agent interface uses the same visible state and actions.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_game_state',description:'Read the current Pengu Run game state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,time:engine.time,price:engine.price,health:engine.health,lane:engine.lane,level:engine.level,speed:engine.speed})},{name:'start_game',description:'Start or restart an endless HP-based Pengu Run game, resetting current progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(input&&Object.keys(input).length)throw Error('No arguments accepted');if(!penguin.naturalWidth)throw Error('Character still loading');start();return{mode,price:engine.price}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
