const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('./engine');
const e=new E(()=>.5);for(let level=1;level<=10;level++){e.time=(level-1)*12;assert.equal(e.level,level);assert.ok(Math.abs(e.speed-(1+(level-1)*.12))<1e-9);if(level>1){assert.ok(e.speed>previousSpeed);assert.ok(e.rowInterval/(e.phase===2?.58:1)<previousInterval)}var previousSpeed=e.speed,previousInterval=e.rowInterval/(e.phase===2?.58:1);}e.time=120;assert.equal(e.level,10);e.reset();assert.equal(e.level,1);
// Rendering uses this same age: at higher levels the same object reaches collision sooner.
for(const t of [0,108]){e.reset();e.time=t;e.nextRow=99;e.entities=[{lane:1,age:2.25,reward:false,type:'red'}];e.step(.05);assert.equal(e.health,t===0?3:2)}
e.reset();e.energy=100;e.updatePrice();assert.ok(Math.abs(e.price-1)<1e-9);
for(const width of [380,1060]){
 let clock=0,frame,images=[],els={},listeners={};const context=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(t,k)=>t[k]||(()=>{})});const el=id=>els[id]??={hidden:false,style:{},classList:{add(){},remove(){}},getContext:()=>context,getBoundingClientRect:()=>({left:20,top:100,width,height:650}),addEventListener:(n,f)=>listeners[id+n]=f,append(){},setAttribute(n,v){this[n]=v}};class Image{constructor(){images.push(this);this.naturalWidth=1536;this.naturalHeight=1024}set src(v){this._src=v}get src(){return this._src}}
 const box={PenguEngine:E,Image,console,document:{getElementById:el,querySelector:el,body:el("body"),documentElement:{},addEventListener(){}},window:{matchMedia:()=>({matches:false}),innerWidth:width,addEventListener:(n,f)=>listeners[n]=f},performance:{now:()=>clock},localStorage:{getItem:()=>null,setItem(){}},requestAnimationFrame:f=>frame=f,setTimeout(){}};vm.createContext(box);vm.runInContext(fs.readFileSync('i18n.js','utf8'),box);box.PenguI18n=box.window.PenguI18n;vm.runInContext(fs.readFileSync('game.js','utf8'),box);el('play').onclick();
 const tap=(fraction,extra={})=>listeners.gamepointerdown({clientX:20+width*fraction,clientY:400,isPrimary:true,pointerType:'touch',button:0,preventDefault(){},...extra});
 for(const [fraction,lane] of [[.1,0],[.9,2],[.5,1],[0,0],[1,2]]){tap(fraction);assert.equal(vm.runInContext('engine.lane',box),lane)}
 tap(.1,{isPrimary:false});assert.equal(vm.runInContext('engine.lane',box),2);tap(.1,{pointerType:'mouse',button:2});assert.equal(vm.runInContext('engine.lane',box),2);
 el('pause').onclick();tap(.1);assert.equal(vm.runInContext('engine.lane',box),2);el('resume').onclick();clock=200;listeners.keydown({key:'ArrowLeft',target:{closest:()=>false},preventDefault(){}});assert.equal(vm.runInContext('engine.lane',box),1);
 vm.runInContext('engine.time=108',box);clock+=50;frame(clock);assert.equal(el('level').textContent,'LEVEL 10 / 10');assert.equal(el('speed').textContent,'2.08×');for(const lang of ['en','ko','ja','zh-Hant']){const state=vm.runInContext('JSON.stringify([engine.time,engine.lane,engine.health,mode])',box);el('language').value=lang;el('language').onchange();assert.equal(box.document.documentElement.lang,lang);assert.equal(vm.runInContext('JSON.stringify([engine.time,engine.lane,engine.health,mode])',box),state);assert.ok(el('.facts [data-fact="0"]').innerHTML.includes('https://'));vm.runInContext('finish()',box);assert.ok(el('result-title').textContent);el('language').value=lang;el('language').onchange();assert.ok(el('coins').textContent);vm.runInContext("mode='running'",box)}
 el('retry').onclick();assert.equal(el('level').textContent,'等級 1 / 10');
}
assert.ok(!fs.readFileSync('index.html','utf8').includes('id="left"'));assert.ok(!fs.readFileSync('index.html','utf8').includes('id="right"'));
console.log('PASS: ten-level progression, collision speed, pricing, mobile/desktop direct taps, input guards, keyboard, pause and retry');

const i18nBox={window:{}};vm.runInNewContext(fs.readFileSync('i18n.js','utf8'),i18nBox);const translations=i18nBox.window.PenguI18n;for(const values of Object.values(translations.keys)){assert.equal(values.length,4);assert.ok(values.every(v=>typeof v==='string'&&v.length));const tokens=v=>[...v.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort().join(',');assert.ok(values.every(v=>tokens(v)===tokens(values[0])))}console.log('PASS: four languages, placeholder parity, source links, result translations and unchanged run state');

// Endless runs and bear-only score penalties, including entry cleanup and phase cycling.
const survival=new E(()=>.5);survival.nextRow=Infinity;for(let i=0;i<2000;i++){survival.entities=[];survival.nextRow=Infinity;survival.step(.05)}assert.ok(survival.time>99);assert.equal(survival.done,false);assert.equal(survival.price,.009);
survival.reset();survival.time=20;survival.energy=50;survival.row();assert.equal(survival.entities.length,2);assert.ok(survival.entities.every(e=>!e.reward&&e.penaltyOnly));for(let i=0;i<3;i++){survival.invulnerable=0;survival.hit(survival.entities[0]);}survival.updatePrice();assert.equal(survival.health,3);assert.equal(survival.energy,23);assert.equal(survival.done,false);assert.equal(survival.coins,0);survival.hit({reward:true,type:'coin',lane:1});assert.equal(survival.coins,0);
survival.reset();survival.time=19.99;survival.entities=[{age:2.34,reward:true,type:'coin',lane:1}];survival.step(.02);assert.ok(survival.entities.every(e=>!e.reward));assert.equal(survival.coins,0);
survival.reset();for(let i=0;i<3;i++){survival.invulnerable=0;survival.hit({reward:false,type:'red',lane:1});survival.step(.01)}assert.equal(survival.health,0);assert.equal(survival.done,true);
for(const [time,phase] of [[0,0],[10,1],[20,2],[32,3],[48,0],[68,2]]){survival.time=time;assert.equal(survival.phase,phase)}
console.log('PASS: no time limit/passive points, bear penalties never damage HP or reward points, clear bear entry, three HP hits end, repeating phases');

const acceleration=new E();let previous=0;for(let i=0;i<=12000;i++){acceleration.time=i/100;assert.ok(acceleration.speed>=previous);previous=acceleration.speed;}for(const boundary of [12,20,24,32,48,68,108]){acceleration.time=boundary-.001;const before=acceleration.speed;acceleration.time=boundary+.001;assert.ok(Math.abs(acceleration.speed-before)<.001)}acceleration.time=6;assert.ok(Math.abs(acceleration.speed-1.06)<1e-9);acceleration.time=108;assert.equal(acceleration.level,10);assert.ok(Math.abs(acceleration.speed-2.08)<1e-9);
console.log('PASS: continuous monotonic speed, no phase/level-boundary jumps, level 10 cap');
